project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - pages/data_processing.qmd
    - pages/data_summarization.qmd
    - pages/data_exploration.qmd
    
website:
  title: "Project 1 Site"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - pages/data_processing.qmd
      - pages/data_summarization.qmd
      - pages/data_exploration.qmd
  page-navigation: true
  reader-mode: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px

callout-appearance: simple

date: today
date-format: iso
