---
title: "Combining Excel and Delimited Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---
# Task 3
## Problem 1

First, let's import the data!

```{R}
library(readxl)
library(tidyverse)
```

```{R}
wine_data <- read_excel("../white-wine.xlsx")

wine_data
```

## Problem 2
Now that we have the data, let's fix some of the non-standard names. To do this, we can use the second sheet of the dataset to get the names:

```{R}
wine_data_columns <- read_excel("../white-wine.xlsx", sheet = excel_sheets("../white-wine.xlsx") [2])

wine_data_columns
```

Now that we have the correct column names, we can rename the columns in our tibble. Since we have to rename all the columns and have a list of the corrected names, let's use colnames.

```{R}
colnames(wine_data) <- wine_data_columns[[1]]

wine_data
```

## Problem 3
For this task, we can use mutate to add a new column!
```{R}
labeled_wine_data <- wine_data |>
  mutate(type = "white")

labeled_wine_data
```

## Problem 4
Since this data is semi-colon delimited, we would use read_csv2, but since there are decimals in the numeric data, we will use read_delim.

```{R}
wine_data2 <- read_delim("https://www4.stat.ncsu.edu/~online/datasets/red-wine.csv", delim = ";")

wine_data2
```

We can see that the column names include spaces, so let's replace those with our column names from the other dataset.

```{R}
colnames(wine_data2) <- wine_data_columns[[1]]

wine_data2
```

Finally, we can add a new column for the color of the wine.

```{R}
labeled_wine_data2 <- wine_data2 |>
  mutate(type = "red")

labeled_wine_data2
```

## Problem 5

Now, we can simply combine these two tibbles using bind_rows:

```{R}
combined_wine_data <- bind_rows(labeled_wine_data, labeled_wine_data2)

combined_wine_data
```

## Problem 6, 7, 8, and 9

Now, let's start a chain that begins by filtering the data. Then we will sort the output of the filter by descending quality. Next, we use select to only keep columns that contain "acid", alcohol, type, and quality. 

```{R}
altered_wine_data <- combined_wine_data |>
  filter(quality > 6.5, alcohol < 132) |>
  arrange(desc(quality)) |>
  select(contains("acid"), alcohol, type, quality) |>
  group_by(quality) |>
  mutate(across(alcohol, list(mean = mean, sd = sd)))

altered_wine_data
```